# Generated by Django 5.2.15 on 2026-07-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_referralpayoutstatement_email_delivery_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralpayout",
            name="currency",
            field=models.CharField(default="BRL", max_length=3),
        ),
        migrations.AlterField(
            model_name="referralpayoutstatement",
            name="currency",
            field=models.CharField(default="BRL", max_length=3),
        ),
    ]
