# Generated by Django 5.2.15 on 2026-07-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_referralpayout_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reveluser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('it', 'Italiano'), ('fr', 'Français'), ('pt', 'Português')], db_index=True, default='pt', help_text="User's preferred language", max_length=7),
        ),
    ]
