# Generated by Django

from django.db import migrations


def backfill_language_pt(apps, schema_editor):
    """Move existing users off the old 'en' default onto DuRock RJ's actual language.

    DuRock RJ ships a Portuguese-only UI; 'en' was never a deliberate choice here — it
    was Django's global LANGUAGE_CODE leaking into RevelUser's default before this
    migration. Without this backfill, existing users would keep silently missing
    Portuguese notifications (title/body render per user.language) even after the
    model/schema default changed to 'pt' for new signups.
    """
    RevelUser = apps.get_model("accounts", "RevelUser")
    RevelUser.objects.filter(language="en").update(language="pt")


def reverse_noop(apps, schema_editor):
    """No-op: which of the backfilled users were genuinely 'en' before is not recoverable."""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_alter_reveluser_language"),
    ]

    operations = [
        migrations.RunPython(
            backfill_language_pt,
            reverse_code=reverse_noop,
        ),
    ]
