# Generated by Django 5.2.16 on 2026-07-14 03:33

import django.core.validators
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0032_backfill_reveluser_language_pt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="revenue_share_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=accounts.models._default_referral_share_percent,
                help_text="Snapshotted from settings.DEFAULT_REFERRAL_SHARE_PERCENT at creation time",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="referralpayout",
            name="currency",
            field=models.CharField(default=accounts.models._default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name="referralpayoutstatement",
            name="currency",
            field=models.CharField(default=accounts.models._default_currency, max_length=3),
        ),
    ]
