# Generated by Django 5.2.16 on 2026-07-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_referral_revenue_share_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reveluser',
            name='pronouns',
        ),
    ]
