# Generated by Django 5.2.15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0090_attendeeinvoice_email_delivery_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="bands",
            field=models.ManyToManyField(
                blank=True, help_text="Bands lined up for this event.", related_name="events", to="events.band"
            ),
        ),
    ]
