# Generated by Django 5.2.15 on 2026-07-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0091_band_event_bands"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="BRL", max_length=3),
        ),
        migrations.AlterField(
            model_name="platformfeeinvoice",
            name="currency",
            field=models.CharField(default="BRL", help_text="ISO 4217 currency code.", max_length=3),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="currency",
            field=models.CharField(default="BRL", help_text="ISO 4217 currency code", max_length=3),
        ),
    ]
