# Generated by Django 5.2.15 on 2026-07-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0092_alter_payment_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettier",
            name="external_ticket_url",
            field=models.URLField(
                blank=True,
                help_text=(
                    "Where buyers purchase this ticket when it's sold on an external platform "
                    "(e.g. Sympla, Eventbrite). Only used when payment_method is 'external'."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("at_the_door", "At The Door"),
                    ("free", "Free"),
                    ("external", "External"),
                ],
                db_index=True,
                default="offline",
                max_length=20,
            ),
        ),
    ]
