# Generated by Django 5.2.16 on 2026-07-14 03:33

import django.core.validators
from django.db import migrations, models

import events.models.invoice
import events.models.organization
import events.models.ticket


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0094_remove_organization_bluesky_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="platform_fee_fixed",
            field=models.DecimalField(
                decimal_places=2,
                default=events.models.organization._default_platform_fee_fixed,
                help_text="The fixed platform fee for this organization.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="platform_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=events.models.organization._default_platform_fee_percent,
                help_text="The percentage platform fee Revel takes on ticket sales for this organization.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default=events.models.ticket._default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name="platformfeeinvoice",
            name="currency",
            field=models.CharField(
                default=events.models.invoice._default_currency, help_text="ISO 4217 currency code.", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="currency",
            field=models.CharField(
                default=events.models.ticket._default_currency, help_text="ISO 4217 currency code", max_length=3
            ),
        ),
    ]
