# Generated by Django 5.2.16 on 2026-07-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0095_alter_organization_platform_fee_fixed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='public_pronoun_distribution',
        ),
        migrations.AlterField(
            model_name='event',
            name='requires_full_profile',
            field=models.BooleanField(default=False, help_text='Whether this event requires full profile information (profile pic, name)'),
        ),
    ]
