# Generated by Django 5.2.16 on 2026-07-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0097_translate_default_membership_tier_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Stable dedup key from an external ingestion source (e.g. rockfeed-rj). Null for events created in-app.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
