# Generated by Django 5.2.16 on 2026-07-23 00:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0099_add_scraper_system_user_and_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedExternalEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("external_uid", models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "Deleted external event",
                "verbose_name_plural": "Deleted external events",
                "ordering": ["-created_at"],
            },
        ),
    ]
