# Generated by Django 5.2.16 on 2026-07-24 14:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0100_deletedexternalevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerAlias",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("raw_name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_aliases",
                        to="events.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizer alias",
                "verbose_name_plural": "Organizer aliases",
                "ordering": ["raw_name"],
            },
        ),
    ]
