# Generated by Django 5.2.16 on 2026-07-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0101_organizeralias'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pix_key',
            field=models.CharField(blank=True, default='', help_text="Pix key (CPF, CNPJ, email, phone, or random/EVP key) receiving payments for this organization's Pix ticket tiers. Blank disables the Pix payment method.", max_length=140),
        ),
    ]
