# Generated by Django 5.2.16 on 2026-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0102_add_organization_pix_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettier',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('at_the_door', 'At The Door'), ('free', 'Free'), ('external', 'External'), ('pix', 'Pix')], db_index=True, default='offline', max_length=20),
        ),
    ]
