# Generated by Django 5.2.16 on 2026-07-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_add_pix_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pix_reference',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Short reference embedded in the Pix QR code's txid field, shared by every ticket in the same Pix batch checkout. Lets the organizer match an incoming Pix payment (by its txid) back to the buyer/event when confirming payment manually.", max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid per ticket for PWYC offline/at_the_door/Pix purchases. Null for online payments (stored in Payment.amount) or fixed-price tiers (use tier.price).', max_digits=10, null=True),
        ),
    ]
