# Generated by Django 5.2.15 on 2026-07-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_alter_fileexport_export_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="base",
            field=models.CharField(default="BRL", max_length=3),
        ),
    ]
