# Generated by Django 5.2.16 on 2026-07-14 03:33

from django.db import migrations, models

import common.models.exchange
import common.models.site


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_seed_legal_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="base",
            field=models.CharField(default=common.models.exchange._default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name="historicalsitesettings",
            name="frontend_base_url",
            field=models.URLField(default=common.models.site._default_frontend_base_url),
        ),
        migrations.AlterField(
            model_name="historicalsitesettings",
            name="internal_catchall_email",
            field=models.EmailField(
                default=common.models.site._default_internal_catchall_email,
                help_text="The catchall email address for internal use.",
                max_length=254,
                verbose_name="Internal Catchall Email",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="frontend_base_url",
            field=models.URLField(default=common.models.site._default_frontend_base_url),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="internal_catchall_email",
            field=models.EmailField(
                default=common.models.site._default_internal_catchall_email,
                help_text="The catchall email address for internal use.",
                max_length=254,
                verbose_name="Internal Catchall Email",
            ),
        ),
    ]
